In [ ]:
import numpy as np
data = np.sin(np.arange(20)).reshape(5,4)
print (data)
ind = data.argmax(axis=0)       # data.argmax 寻找最大值  axis=0按列查找  axis=1按行查找
print (ind)
data_max = data[ind, range(data.shape[1])]      #取出值
print (data_max)
all(data_max == data.max(axis=0))

In [5]:
a = np.arange(0, 40, 10)         # arange 生成矩阵 (最小值，最大值，等差值)
b = np.tile(a, (3, 2))           # 扩展 tile (a,(行*倍，列*倍)) 
print (b)

[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


a = np.arange(0, 40, 10)
print a
print '---'
b = np.tile(a, (1, 4))
print b
#print a
#print b


In [18]:
a = np.array([[4, 3, 5], [1, 2, 1]])
print (a)
print ("-----1-----")
b = np.sort(a, axis=1)                #  sort 排序   axis=1按行    
print (b)
print ("-----2-----")
#b
#a.sort(axis=1)
#print a
a = np.array([4, 3, 1, 2])
j = np.argsort(a)                   # argsort 最大值索引
print (j)
print (a[j])                        #按索引排序

[[4 3 5]
 [1 2 1]]
-----1-----
[[3 4 5]
 [1 1 2]]
-----2-----
[2 3 1 0]
[1 2 3 4]
