In [2]:
import numpy as np
B = np.arange(3)
print (B)
print (np.exp(B))              # e 幂
print (np.sqrt(B))             # 根 号

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [14]:
#Return the floor of the input
a = np.floor(10*np.random.random((3,4)))             # floor向下取整
print (a)
print ("----------")
#a.shape
## flatten the array
print (a.ravel())                                    # ravel 矩阵拉平
print ("----------")                                
a.shape = (6, 2)                                    # shape 变换矩阵格式
#print a 
print ("1----------")
print (a.T)                                         #  a.T 转置      
print ("2----------")
print (a.shape)
print ("3----------")
print (a)

#If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
#a.reshape(3,-1)                                   

[[8. 9. 5. 2.]
 [4. 6. 1. 6.]
 [8. 7. 2. 4.]]
----------
[8. 9. 5. 2. 4. 6. 1. 6. 8. 7. 2. 4.]
----------
1----------
[[8. 5. 4. 1. 8. 2.]
 [9. 2. 6. 6. 7. 4.]]
2----------
(6, 2)
3----------
[[8. 9.]
 [5. 2.]
 [4. 6.]
 [1. 6.]
 [8. 7.]
 [2. 4.]]


In [32]:
import numpy as np                                   #矩阵拼接
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print a
print '---'
print b
print '---'
print np.hstack((a,b))                   # hstack 按行拼接     vstack 按列拼接      
#np.hstack((a,b))

[[ 5.  6.]
 [ 1.  5.]]
---
[[ 8.  6.]
 [ 9.  0.]]
---
[[ 5.  6.  8.  6.]
 [ 1.  5.  9.  0.]]


In [29]:
a = np.floor(10*np.random.random((2,12)))             #切分
print (a)
print (np.hsplit(a,3))                                # hsplit  (a,分几份)  横向切割
print (np.hsplit(a,(3,4)))                            #指定切割 (a,(b,c)) b,c 切割
# Split a after the third and the fourth column
a = np.floor(10*np.random.random((12,2)))
print (a)                                         
np.vsplit(a,3)                                        # vsolit  (a,分几份)  竖向切割

[[2. 3. 7. 7. 6. 8. 8. 4. 1. 5. 9. 6.]
 [0. 1. 3. 4. 5. 0. 7. 2. 2. 9. 0. 4.]]
[array([[2., 3., 7., 7.],
       [0., 1., 3., 4.]]), array([[6., 8., 8., 4.],
       [5., 0., 7., 2.]]), array([[1., 5., 9., 6.],
       [2., 9., 0., 4.]])]
[array([[2., 3., 7.],
       [0., 1., 3.]]), array([[7.],
       [4.]]), array([[6., 8., 8., 4., 1., 5., 9., 6.],
       [5., 0., 7., 2., 2., 9., 0., 4.]])]
[[0. 4.]
 [9. 4.]
 [0. 4.]
 [5. 0.]
 [2. 8.]
 [4. 5.]
 [1. 2.]
 [6. 6.]
 [4. 6.]
 [6. 1.]
 [9. 0.]
 [3. 1.]]


[array([[0., 4.],
        [9., 4.],
        [0., 4.],
        [5., 0.]]), array([[2., 8.],
        [4., 5.],
        [1., 2.],
        [6., 6.]]), array([[4., 6.],
        [6., 1.],
        [9., 0.],
        [3., 1.]])]

In [30]:
#Simple assignments make no copy of array objects or of their data.
a = np.arange(12)
b = a
# a and b are two names for the same ndarray object
b is a
b.shape = 3,4
print (a.shape)
print (id(a))
print (id(b))

(3, 4)
2403132654176
2403132654176


In [38]:
#The view method creates a new array object that looks at the same data.
c = a.view()                        # a.view  改变格式  共用值 
print (c is a)
c.shape = 2,6
print (a.shape)
c[0,4] = 1234 
print (c)
print ("----------")
print (a)

False
(3, 4)
[[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]
----------
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [46]:
#The copy method makes a complete copy of the array and its data.
d = a.copy()                      #a.copy   改变格式     改变值
d is a
d[0,0] = 9999
print d 
print a

[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
